### PR TITLE
[excel] (Create Workbook) Update create worksheet from website sample to no longer use VS

### LINKED ISSUE #938: Create worksheet from website sample doesn't run in VS
> Note: This template is only for reporting bugs about samples in this repo. If you have a product bug to report about Office web Add-ins, please submit the issue at [https://github.com/OfficeDev/office-js/issues](https://github.com/OfficeDev/office-js/issues/new). This will help us respond to your issue faster.
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

**URL of sample**

https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/excel-create-worksheet-from-web-site

**Describe the bug**

When running the Visual Studio project, you get a note saying project is a class library and can't be run.

**To Reproduce**

1. Open the VS Solution.
2. Press F5.

**Expected behavior**

The Azure Function launches.

**Screenshots**

Image

**Environment**
- Platform [PC desktop, Mac, iOS, Office Online]: Windows
- Host [Excel, Word, PowerPoint, etc.]: Excel
- Office version number: N/A
- Operating System: Windows 11
- Browser (if using Office Online): N/A

**Additional context**

### PR DESCRIPTION
**Pull request by AlexJerabek**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | yes                               |
| New feature?    | no                           |
| New sample?     | no |
| Related issues? | fixes #938  |

## What's in this Pull Request?

The sample has been reworked to no longer Visual Studio. This fixed the bugs we made along the way.

### CODE REVIEW

File: Samples/excel-create-worksheet-from-web-site/server.js [hunk 1]
```diff
@@ -0,0 +1,135 @@
...
+// Configure morgan module to log all requests.
+app.use(morgan('dev'));
+
+// Parse JSON bodies
+app.use(express.json());
+
+// Setup app folders.
+app.use(express.static('WebApplication/App'));
+
+// API endpoint to create spreadsheet
```
Comment (davidchesnut) [inline Samples/excel-create-worksheet-from-web-site/server.js:23]:
```suggestion
// API endpoint to create spreadsheet
// Security note: This API is public and can be called by any client. Be sure to add authentication and authorization for this API in a production environment.
```

File: Samples/excel-create-worksheet-from-web-site/README.md [hunk 2]
```diff
@@ -55,21 +55,23 @@ or download and extract the repository *.zip* file.
...
 ```
 
 ### Step 3: Register the sample application(s) in your tenant
 
-#### Choose the Azure AD tenant where you want to create your applications
+#### Choose the Microsoft Entra ID tenant where you want to create your applications
 
 1. Sign in to the [Azure portal](https://portal.azure.com).
-1. If your account is present in more than one Azure AD tenant, select your profile at the top right corner in the menu on top of the page, and then **switch directory** to change your portal session to the desired Azure AD tenant.
+1. If your account is present in more than one Microsoft Entra ID tenant, select your profile at the top right corner in the menu on top of the page, and then **switch directory** to change your portal session to the desired Microsoft Entra ID tenant.
```
Comment (davidchesnut) [inline Samples/excel-create-worksheet-from-web-site/README.md]: could delete this step about signing in when you have multiple tenants. We don't include this in similar samples with app registrations as folks should know which account to use to sign in and set this up.

File: Samples/excel-create-worksheet-from-web-site/README.md [hunk 3]
```diff
@@ -148,68 +146,75 @@ This sample was built using the code from [Vanilla JavaScript single-page applic
...
 
 ## Security notes
 
-- There may be security issues in packages used by this sample. Be sure to run `npm audit` to identify any security vulnerabilities.
-- In the `FunctionCreateSpreadsheet/FunctionCreateSpreadsheet/local.settings.json` file, "CORS" is set to "*". This is only for development purposes. In production code, you should list the allowed domains and not leave this header open to all domains.
+- There may be security issues in packages used by this sample. Be sure to run `npm audit` to identify any security vulnerabilities and update packages regularly.
+- This sample runs on `localhost` for development purposes only. In production, you should:
+  - Use HTTPS
+  - Implement proper CORS configuration
+  - Add authentication and authorization for the API endpoint
```
Comment (davidchesnut) [inline Samples/excel-create-worksheet-from-web-site/README.md:223]: aha the notes are already here! :-)

**Review by davidchesnut — COMMENTED** [review]
Looks good. I will check in a change to update the app registration steps.

**Review by davidchesnut — APPROVED** [review]
added updated steps for app registration
